[banner]
color = "red"
command = """
echo '                    __                        __      __  ' &&
echo '   _______  _______/ /_      ____ ___  ____  / /_____/ /  ' &&
echo '  / ___/ / / / ___/ __/_____/ __ `__ \\/ __ \\/ __/ __  / ' &&
echo ' / /  / /_/ (__  ) /_/_____/ / / / / / /_/ / /_/ /_/ /    ' &&
echo '/_/   \\__,_/____/\\__/     /_/ /_/ /_/\\____/\\__/\\__,_/'"""

[weather]
loc = "New York, New York"

[service_status]
Accounts = "accounts-daemon"
Cron = "cronie"

[uptime]
prefix = "Up"

[ssl_certificates]
sort_method = "alphabetical"

    [ssl_certificates.certs]
    "example.com" = "./cert.pem"

[filesystems]
root = "/"

[memory]
swap_pos = "beside"

[fail_2_ban]
jails = ["sshd"]

[last_login]
marcel = 2

[load_avg]
format = "Load (1, 5, 15 min.): {one:.02}, {five:.02}, {fifteen:.02}"

[last_run]
